# Generated by Django 2.1.7 on 2019-02-14 05:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('hair_color', models.CharField(max_length=20)),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.DateField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Audience')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(editable=False, max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.CharField(editable=False, max_length=60, primary_key=True, serialize=False)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.AdType')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Audience')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Campaign')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Date')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Action')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.AdType')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Audience')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Campaign')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Date')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Source')),
                ('spend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Spend')),
            ],
        ),
        migrations.AddField(
            model_name='audience',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer_assignment.Campaign'),
        ),
    ]
